name: Documentation
on:
  pull_request:
  merge_group:

env:
  DOXY_VER: '1.9.6'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Build_Doc:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: 'true'
          lfs: 'true'

      - name: Install apt-get dependencies
        uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad # v1.4.2
        with:
          packages: graphviz texlive liblua5.2-0 libclang1-9 libclang-cpp9
          version: 3.0

      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        id: cp310
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            docs/requirements.txt
            docs/openvino_sphinx_theme/setup.py

      - name: Install python dependencies
        run: |
          python3 -m pip install -r docs/requirements.txt
          (cd docs/openvino_sphinx_theme && python3 setup.py install)
          python3 -m pip install docs/openvino_custom_sphinx_sitemap

      - name: Download and install doxygen
        run: |
          # install doxygen
          wget https://www.doxygen.nl/files/doxygen-$DOXY_VER.linux.bin.tar.gz
          tar -xzf doxygen-$DOXY_VER.linux.bin.tar.gz
          echo "$(pwd)/doxygen-$DOXY_VER/bin/" >> $GITHUB_PATH

      - name: Build docs
        run: |
          rm -rf build && mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_DOCS=ON
          cmake --build . --target sphinx_docs

      - name: Cache documentation
        id: cache_sphinx_docs
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: build/docs/_build/.doctrees
          key: sphinx-docs-cache

      - name: Archive docs HTML
        run: (cd build/docs && zip -r openvino_docs_html.zip _build)

      - name: Set PR number
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: 'Upload sphinx.log'
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: sphinx_build_log_${{ env.PR_NUMBER }}.log
          path: build/docs/sphinx.log

      - name: 'Upload docs html'
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: openvino_docs_html_${{ env.PR_NUMBER }}.zip
          path: build/docs/openvino_docs_html.zip

      - name: Run Pytest
        run: |
          pytest --sphinx="./build/docs/sphinx.log" \
                 --suppress-warnings="./docs/scripts/tests/suppress_warnings.txt" \
                 --confcutdir="./docs/scripts/tests/" \
                 --html="./build/docs/_artifacts/doc-generation.html" \
                 --sphinx-strip="$(pwd)/build/docs/sphinx_source" \
                 --xfail="./docs/scripts/tests/xfail.txt" \
                 --self-contained-html ./docs/scripts/tests/test_docs.py

      - name: 'Upload test results'
        if: failure()
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: openvino_docs_pytest
          path: build/docs/_artifacts/
