name: Code Style
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: 'true'

      - name: Install clang-format-15
        run: |
          sudo apt update
          sudo apt --assume-yes install clang-format-15

      # Run cmake with -DENABLE_PROFILING_ITT=ON -DSELECTIVE_BUILD=COLLECT in order to enable codestyle check for ITT collector
      - name: CMake configure
        run: cmake -DENABLE_PYTHON=ON -DENABLE_TESTS=ON -DENABLE_PROFILING_ITT=ON -DSELECTIVE_BUILD=COLLECT -B build

      - name: Create code style diff
        run: cmake --build build --target clang_format_fix_all -j8

      - name: suggester / clang-format
        if: startsWith(github.event_name, 'pull_request')
        uses: reviewdog/action-suggester@63b8f8cc21dfa052ac44436e65ed31edcffcb6c1 # v1.17.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning
          fail_on_error: true

  ShellCheck:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: 'true'

      - name: Install ShellCheck
        run: |
          sudo apt update
          sudo apt --assume-yes install shellcheck

      - name: CMake configure
        run: cmake -B build

      - name: Shellcheck cmake target
        run: cmake --build build --target ov_shellcheck -j8

      # always provide suggestions even for skipped scripts in ov_shellcheck tagret
      - name: ShellCheck action
        if: always()
        uses: reviewdog/action-shellcheck@d99499e855260c9c56f7a1d066933b57326e9e7c # v1.26.0
        with:
          level: style
          reporter: github-pr-review
          check_all_files_with_shebangs: true
          fail_on_error: true
          exclude: |
              "*/thirdparty/*"
              "./temp/*"

  NamingConventionCheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: 'true'

      - name: Install Clang dependency
        run: |
          sudo apt update
          sudo apt --assume-yes remove clang-7 clang-8 clang-9 clang-10 clang-11 clang-12 clang-13 clang-15
          sudo apt --assume-yes install clang-14 libclang-14-dev

      - name: Install Python-based dependencies
        run: python3 -m pip install -r cmake/developer_package/ncc_naming_style/requirements_dev.txt

      - name: CMake configure
        run: cmake -B build

      - name: Naming convention check
        run: cmake --build build --target ncc_all -j8
